### PR TITLE
Fix build without glutin

### PR DESCRIPTION
**Pull request by Ralith**

### CODE REVIEW

**Comment by ebkalderon** [comment]
I must have accidentally introduced this bug during the refactoring process. I'll release a new version with the fix as soon as possible.

**Comment by ebkalderon** [comment]
Thanks a lot, @Ralith! A new Crates.io release should be incoming soon.

**Comment by ebkalderon** [comment]
@Ralith Release [0.7.1](https://github.com/ebkalderon/renderdoc-rs/releases/tag/v0.7.1) is out!

**Comment by Ralith** [comment]
Much appreciated!

**Pull request merged**
